version: '3.2' # specify docker-compose version
 
# Define the services/ containers to be run
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: exit_test
    ports:
    - "3307:3306"
    volumes: 
      - db-config:/etc/mysql
      - db-data:/var/lib/mysql    
  

  nginx:
    depends_on:
      - angular
      - node
    restart: always
    build: nginx
    ports:
    - "3050:80"


  angular: 
   build: frontend # specify the directory of the Dockerfile
  # ports:
  # - "4200:4200" # specify port mapping

  node: # name of the second service
    build: backend # specify the directory of the Dockerfile
    environment:
      MYSQL_DATABASE: exit_test
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
      MYSQL_HOST_IP: db
    # ports:
    # - "5000:5000"
    # network_mode: "host"
    depends_on:
      - db


  
volumes:
  db-config:
  db-data:

 